from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Optional

from loguru import logger

from bot.config import settings

HAS_BROWSER_COOKIE3 = False
try:
    import browser_cookie3  # noqa: F401
    HAS_BROWSER_COOKIE3 = True
except ImportError:
    pass


_COOKIES_CACHE: Optional[str] = None


def extract_chrome_cookies() -> Optional[str]:
    global _COOKIES_CACHE
    if _COOKIES_CACHE and Path(_COOKIES_CACHE).exists():
        return _COOKIES_CACHE

    if not HAS_BROWSER_COOKIE3:
        logger.warning("browser-cookie3 not installed. Instagram may not work.")
        return None

    import browser_cookie3

    cookies = None
    try:
        cookies = browser_cookie3.chrome(domain_name=".instagram.com")
    except Exception as e:
        logger.warning(f"Chrome cookie filter failed: {e}")
        try:
            cookies = browser_cookie3.chrome()
        except Exception as e2:
            logger.error(f"Chrome cookie extraction failed: {e2}")

    if not cookies:
        try:
            cookies = browser_cookie3.firefox(domain_name=".instagram.com")
        except Exception:
            pass

    if not cookies:
        logger.warning(
            "No Instagram cookies found in any browser.\n"
            "Either run the bot as ADMINISTRATOR,\n"
            "or manually save cookies.txt from Chrome extension 'Get cookies.txt' and put in downloads/ folder."
        )
        return None

    output_file = str(Path(settings.DOWNLOAD_DIR) / "instagram_cookies.txt")

    try:
        with open(output_file, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by browser-cookie3\n\n")
            for c in cookies:
                domain = c.domain or ".instagram.com"
                flag = "TRUE" if domain.startswith(".") else "FALSE"
                path = c.path or "/"
                secure = "TRUE" if c.secure else "FALSE"
                expires = str(int(c.expires)) if c.expires else "0"
                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{c.name}\t{c.value}\n")

        _COOKIES_CACHE = output_file
        logger.info(f"Extracted {len(cookies)} Instagram cookies to {output_file}")
        return output_file
    except Exception as e:
        logger.error(f"Failed to write cookies file: {e}")
        return None


def ensure_instagram_cookies() -> Optional[str]:
    manual = settings.DOWNLOAD_DIR / "instagram_cookies.txt"
    if manual.exists():
        logger.info(f"Using manual cookies file: {manual}")
        return str(manual)
    return extract_chrome_cookies()
